name: IgniteExample
options:
  bundleIdPrefix: pl.codeforge
attributes:
  ORGANIZATIONNAME: "IgniteExample"
packages:
  Ignite:
    path: ..
  Singularity:
    url: https://github.com/gsagadyn/Singularity.git
    from: 1.0.0
targets:
  IgniteExample:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [IgniteExample]
    dependencies:
      - package: Ignite
      - package: Singularity